site_name: 'JAX-LaB'
site_description: 'Documentation for project JAX-LaB'

docs_dir: docs

repo_name: 'piyush-ppradhan/JAX-LaB'
repo_url: https://github.com/piyush-ppradhan/JAX-LaB
edit_uri: edit/multiphase/docs/

watch:
- ./src/

theme:
  name: material
  features:
    - header.autohide
  font:
    text: Ubuntu
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - tables
  - toc
  - smarty
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      anchor_linenums: true
      linenums_style: table
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ['.']
      check_paths: true

plugins:
  - search
  - autolinks
  - mkdocstrings:
      handlers:
        python:
          options:
            separate_signature: true
            show_root_heading: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - API:
    - Base: base.md
    - Boundary Conditions: boundary_conditions.md
    - Models: models.md
    - Multiphase: multiphase.md
    - Equations of State: eos.md
    - Lattice: lattice.md
    - Precision Policy: precision_policy.md
    - Utilities: utils.md
